-- 1. 법률칼럼 관리를 위한 테이블 생성
CREATE TABLE legal_columns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  summary TEXT,
  content TEXT NOT NULL,
  category TEXT DEFAULT '법률칼럼',
  author_name TEXT DEFAULT '대표변호사',
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 보안 정책 해제 (테스트용)
ALTER TABLE legal_columns DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE legal_columns TO anon, authenticated, postgres;
