-- 1. 고객의 상세 폼 데이터에 딱 맞춘 상담 테이블 생성
DROP TABLE IF EXISTS public.consultations;

CREATE TABLE public.consultations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  case_type TEXT, -- 사건 유형 (아파트 하자, 손해배상 등)
  location TEXT, -- 부동산 명칭/위치
  details TEXT, -- 상세 내용
  appointment_time TEXT, -- 희망 상담 시간
  status TEXT DEFAULT '대기중', -- 신규/확인중/완료 상태 관리
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 보안 정책 해제 (누구나 폼으로 제출할 수 있도록 허용)
ALTER TABLE public.consultations DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.consultations TO anon, authenticated, postgres;
