-- 언론보도 내역을 저장할 테이블 생성
CREATE TABLE public.press_releases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,          -- 기사 제목
  press_name TEXT NOT NULL,     -- 언론사명 (예: 조선일보, KBS 등)
  publish_date DATE NOT NULL,   -- 기사 발행일
  external_url TEXT,            -- 뉴스 기사 원문 링크 (있을 경우)
  image_url TEXT,               -- 기사 대표 이미지 (썸네일)
  content TEXT,                 -- 상세 내용 (직접 작성 시 사용)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 보안 정책 해제 (개발 편의를 위해)
ALTER TABLE public.press_releases DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.press_releases TO anon, authenticated, postgres;
