-- 1. 유튜브 영상 관리를 위한 테이블 생성
CREATE TABLE youtube_videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  youtube_id TEXT NOT NULL,
  category TEXT DEFAULT '하자소송',
  theme TEXT DEFAULT 'light',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 보안 정책 설정 (테스트를 위해 모두 허용)
ALTER TABLE youtube_videos DISABLE ROW LEVEL SECURITY;
